package org.tensin.beerduino.run;

import org.apache.log4j.BasicConfigurator;
import org.tensin.beerduino.Preferences;
import org.tensin.beerduino.TemperatureResults;
import org.tensin.common.tools.documentation.updater.SimpleXMLDocumentation;
import org.tensin.common.tools.documentation.updater.SimpleXMLDocumentationOutputMarkdown;
import org.tensin.common.tools.documentation.updater.SimpleXMLDocumentationOutputXSD;

/**
 * The Class UpdateDocumentation.
 */
public class UpdateDocumentation {

    /**
     * Method.
     * 
     * @param args
     *            the arguments
     * @throws Exception
     *             the exception
     */
    public static void main(final String[] args) throws Exception {
        BasicConfigurator.configure();

        // Update the references XSD stored in the code
        SimpleXMLDocumentation.convert(TemperatureResults.class, "src/main/java/org/tensin/beerduino/xsd/temperatureresults.xsd", new SimpleXMLDocumentationOutputXSD());
        SimpleXMLDocumentation.convert(Preferences.class, "src/main/java/org/tensin/beerduino/xsd/preferences.xsd", new SimpleXMLDocumentationOutputXSD());

        // Update the Eclipse XSD used in the project itself under Eclipse (same content as above)
        SimpleXMLDocumentation.convert(Preferences.class, "beerduino.xsd", new SimpleXMLDocumentationOutputXSD());

        // Update the README file with the configuration options and the XML temperature results content
        SimpleXMLDocumentationOutputMarkdown output = new SimpleXMLDocumentationOutputMarkdown();

        output.setBaseReplacementToken("AUTOGENERATED_CONTENT_PREFERENCES");
        SimpleXMLDocumentation.convert(Preferences.class, "../README", output);

        output.setBaseReplacementToken("AUTOGENERATED_CONTENT_TEMPERATURES_RESULTS");
        SimpleXMLDocumentation.convert(TemperatureResults.class, "../README", output);
    }
}
