package org.tensin.beerduino.run;

import org.apache.log4j.BasicConfigurator;
import org.tensin.beerduino.Preferences;
import org.tensin.beerduino.TemperatureResults;
import org.tensin.common.tools.documentation.updater.SimpleXMLDocumentation;
import org.tensin.common.tools.documentation.updater.SimpleXMLDocumentationOutputMarkdown;
import org.tensin.common.tools.documentation.updater.SimpleXMLDocumentationOutputXSD;

/**
 * The Class UpdateDocumentation.
 */
public class UpdateDocumentation {

    /** TOKEN_README_TEMPERATURE_RESULTS */
    private static final String TOKEN_README_TEMPERATURE_RESULTS = "AUTOGENERATED_CONTENT_TEMPERATURES_RESULTS";

    /** TOKEN_README_PREFERENCES */
    private static final String TOKEN_README_PREFERENCES = "AUTOGENERATED_CONTENT_PREFERENCES";

    /** ECLIPSE_XSD_PREFERENCES_FILENAME */
    private static final String ECLIPSE_XSD_PREFERENCES_FILENAME = "beerduino.xsd";

    /** SOURCE_XSD_TEMPERATURE_RESULTS_FILENAME */
    private static final String SOURCE_XSD_TEMPERATURE_RESULTS_FILENAME = "src/main/java/org/tensin/beerduino/xsd/temperatureresults.xsd";

    /** SOURCE_XSD_PREFERENCES_FILENAME */
    private static final String SOURCE_XSD_PREFERENCES_FILENAME = "src/main/java/org/tensin/beerduino/xsd/preferences.xsd";

    /** README_FILENAME */
    private static final String README_FILENAME = "../README.md";

    /**
     * Method.
     * 
     * @param args
     *            the arguments
     * @throws Exception
     *             the exception
     */
    public static void main(final String[] args) throws Exception {
        BasicConfigurator.configure();

        // Update the references XSD stored in the code
        SimpleXMLDocumentation.convert(TemperatureResults.class, SOURCE_XSD_TEMPERATURE_RESULTS_FILENAME, new SimpleXMLDocumentationOutputXSD());
        SimpleXMLDocumentation.convert(Preferences.class, SOURCE_XSD_PREFERENCES_FILENAME, new SimpleXMLDocumentationOutputXSD());

        // Update the Eclipse XSD used in the project itself under Eclipse (same content as above)
        SimpleXMLDocumentation.convert(Preferences.class, ECLIPSE_XSD_PREFERENCES_FILENAME, new SimpleXMLDocumentationOutputXSD());

        // Update the README file with the configuration options and the XML temperature results content
        SimpleXMLDocumentationOutputMarkdown output = new SimpleXMLDocumentationOutputMarkdown();

        output.setBaseReplacementToken(TOKEN_README_PREFERENCES);
        SimpleXMLDocumentation.convert(Preferences.class, README_FILENAME, output);

        output.setBaseReplacementToken(TOKEN_README_TEMPERATURE_RESULTS);
        SimpleXMLDocumentation.convert(TemperatureResults.class, README_FILENAME, output);
    }
}
