package org.tensin.common.tools.documentation.updater;

import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

import org.apache.commons.lang.StringUtils;

/**
 * The Class SimpleXMLDocumentationOutputAPT.
 */
public class SimpleXMLDocumentationOutputAPT implements ISimpleXMLDocumentationOutput {

    /** DEFAULT_BASE_REPLACEMENT_TOKEN. */
    private static final String DEFAULT_BASE_REPLACEMENT_TOKEN = "AUTOGENERATED_CONTENT";

    /** syntaxer. */
    protected ISyntaxer syntaxer;

    /** baseReplacementToken. */
    private String baseReplacementToken = DEFAULT_BASE_REPLACEMENT_TOKEN;

    /**
     * Method.
     * 
     * @param currentEntity
     *            the current entity
     * @param alreadyDisplayed
     *            the already displayed
     * @return the string
     */
    protected String format(final SimpleXMLDocumentationEntity currentEntity, final Set<String> alreadyDisplayed) {
        /* Doublons */
        // currentEntity.checkDoublons(currentEntity.getType().getBaliseName(), currentEntity.getType().getName());

        /* Titre */
        StringBuffer sb = new StringBuffer();
        sb.append(syntaxer.buildLink(currentEntity.getType().getAnchor())).append("\n\n");
        sb.append("    " + currentEntity.getType().getDescription() + "\n\n");

        /* Exemple */
        StringBuffer sbExemple = new StringBuffer(syntaxer.buildUnorderedItem("Exemple"));
        sbExemple.append(syntaxer.buildQuoteStart());
        sbExemple.append("<" + currentEntity.getType().getBaliseName());

        /* Enum */
        if (currentEntity.getType().isEnum()) {
            StringBuffer sbEnum = new StringBuffer(syntaxer.buildUnorderedItem("Enumeration"));
            sbEnum.append(syntaxer.buildTableHeader(new String[] { syntaxer.fontBold("Valeur") }));
            // sbEnum.append("*-----------------+\n");
            // sbEnum.append("| <<Valeur>>      |\n");
            // sbEnum.append("*-----------------+\n");
            List<String> enumerations = currentEntity.getType().getEnumeration();
            for (String enumeration : enumerations) {
                sbEnum.append(syntaxer.buildTableRow(new String[] { enumeration }));
                // sbEnum.append("| " + enumeration + "|\n");
                // sbEnum.append("*-----------------+\n");
            }
            sbEnum.append(syntaxer.buildTableFooter());
            sb.append(sbEnum + "\n\n");
        }

        /* Attributs */
        int initialAttributeLineSize = ("<" + currentEntity.getType().getBaliseName()).length();
        int currentAttributeLineSize = initialAttributeLineSize;
        String currentAttributeLine = "";
        int nbAttributs = 0;
        StringBuffer sbAttributs = new StringBuffer(syntaxer.buildUnorderedItem("Attributs"));
        sbAttributs.append(syntaxer.buildTableHeader(new String[] {
                syntaxer.fontBold("Attributs"),
                syntaxer.fontBold("Type"),
                syntaxer.fontBold("Req"),
                syntaxer.fontBold("Description")

        }));
        // sbAttributs.append("*-----------------+-------------------+-------*-------------------+\n");
        // sbAttributs.append("| <<Attributs>>   | <<Type>>          |<<Req>>| <<Description>>   |\n");
        // sbAttributs.append("*-----------------+-------------------+-------*-------------------+\n");
        Iterator<String> itEntities = currentEntity.getEntities().keySet().iterator();
        while (itEntities.hasNext()) {
            String name = itEntities.next();
            SimpleXMLDocumentationEntity entity = currentEntity.getEntities().get(name);
            if (entity.isAttribute()) {
                nbAttributs++;
                sbAttributs.append(syntaxer.buildTableRow(new String[] {
                        entity.getBaliseName(),
                        getLink(entity),
                        getRequired(entity),
                        entity.getDescription()
                }));
                // sbAttributs.append("| " + entity.getBaliseName() + " | " + getLink(entity) + " | " + getRequired(entity) + " | " + entity.getDescription() + " |\n");
                // sbAttributs.append("*-----------------+-------------------+-------*-------------------+\n");

                String attributeExemple = " " + entity.getBaliseName() + "='...'";
                if (currentAttributeLineSize + attributeExemple.length() > 80) {
                    sbExemple.append(currentAttributeLine + "\n");
                    currentAttributeLine = StringUtils.repeat(" ", initialAttributeLineSize);
                    currentAttributeLineSize = initialAttributeLineSize;
                }
                currentAttributeLine += attributeExemple;
                currentAttributeLineSize += attributeExemple.length();

            }
        }
        sbAttributs.append(syntaxer.buildTableFooter());
        sbExemple.append(currentAttributeLine + ">");
        if (nbAttributs > 0) {
            sb.append(sbAttributs + "\n\n");
        }

        /* Element */
        int nbElements = 0;
        StringBuffer sbElements = new StringBuffer(syntaxer.buildUnorderedItem("Elements"));
        sbElements.append(syntaxer.buildTableHeader(new String[] {
                syntaxer.fontBold("Elements"),
                syntaxer.fontBold("Type"),
                syntaxer.fontBold("Req"),
                syntaxer.fontBold("Description")

        }));
        // sbElements.append("*-----------------+-------------------+-------*-------------------+\n");
        // sbElements.append("| <<Elements>>    | <<Type>>          |<<Req>>| <<Description>>   |\n");
        // sbElements.append("*-----------------+-------------------+-------*-------------------+\n");
        itEntities = currentEntity.getEntities().keySet().iterator();
        while (itEntities.hasNext()) {
            String name = itEntities.next();
            SimpleXMLDocumentationEntity entity = currentEntity.getEntities().get(name);
            if (entity.isElement()) {
                nbElements++;
                sbElements.append(syntaxer.buildTableRow(new String[] {
                        entity.getBaliseName(),
                        getLink(entity),
                        getRequired(entity),
                        entity.getDescription()
                }));
                // sbElements.append("| " + entity.getBaliseName() + " | " + getLink(entity) + " | " + getRequired(entity) + " | " + entity.getDescription() + " |\n");
                // sbElements.append("*-----------------+-------------------+-------*-------------------+\n");
                // sbElements.append("*-----------------+-------------------+---+-------------------+\n");

                sbExemple.append("\n   <!-- Description de '" + entity.getBaliseName() + "' -->");
                sbExemple.append("\n   <" + entity.getBaliseName() + ">");
                if (entity.isPrimitive()) {
                    sbExemple.append(". . .");
                } else {
                    sbExemple.append("\n   . . .\n   ");
                }
                sbExemple.append("</" + entity.getBaliseName() + ">\n");
            } else if (entity.isElementList()) {
                nbElements++;
                if (entity.isInline()) {
                    sbElements.append(syntaxer.buildTableRow(new String[] {
                            "Liste de " + getLink(entity),
                            getLink(entity),
                            getRequired(entity),
                            entity.getDescription()
                    }));
                    // sbElements.append("| Liste de " + getLink(entity) + " | " + getLink(entity) + " | " + getRequired(entity) + " | " + entity.getDescription() + " |\n");

                    sbExemple.append("\n   <!-- Liste de '" + entity.getType().getBaliseName() + "' -->");
                    sbExemple.append("\n   <" + entity.getType().getBaliseName() + ">");
                    sbExemple.append("\n   . . .");
                    sbExemple.append("\n   </" + entity.getType().getBaliseName() + ">");
                    sbExemple.append("\n   .");
                    sbExemple.append("\n   .");
                    sbExemple.append("\n   .");
                    sbExemple.append("\n   <" + entity.getType().getBaliseName() + ">");
                    sbExemple.append("\n   . . .");
                    sbExemple.append("\n   </" + entity.getType().getBaliseName() + ">\n");
                } else {
                    sbElements.append(syntaxer.buildTableRow(new String[] {
                            entity.getBaliseName(),
                            getLink(entity),
                            getRequired(entity),
                            entity.getDescription()
                    }));
                    // sbElements.append("| " + entity.getBaliseName() + " | Liste de " + getLink(entity) + " | " + getRequired(entity) + " | " + entity.getDescription() + " |\n");
                    sbExemple.append("\n   <!-- Description de '" + entity.getBaliseName() + "' -->");
                    sbExemple.append("\n   <" + entity.getBaliseName() + ">");
                    sbExemple.append("\n   . . .");
                    sbExemple.append("\n   </" + entity.getBaliseName() + ">\n");
                }
            }
        }
        if (nbElements > 0) {
            sbElements.append(syntaxer.buildTableFooter());
            sb.append(sbElements).append("\n\n");
        }

        /* Text */
        int nbTexts = 0;
        StringBuffer sbTexts = new StringBuffer(syntaxer.buildUnorderedItem("Contenu"));
        sbTexts.append(syntaxer.buildTableHeader(new String[] {
                syntaxer.fontBold("Type"),
                syntaxer.fontBold("Req"),
                syntaxer.fontBold("Description")

        }));
        // sbTexts.append("*-------------------+-------*-------------------+\n");
        // sbTexts.append("| <<Type>>          |<<Req>>| <<Description>>   |\n");
        // sbTexts.append("*-------------------+-------*-------------------+\n");
        itEntities = currentEntity.getEntities().keySet().iterator();
        while (itEntities.hasNext()) {
            String name = itEntities.next();
            SimpleXMLDocumentationEntity entity = currentEntity.getEntities().get(name);
            if (entity.isText()) {
                nbTexts++;
                sbTexts.append(syntaxer.buildTableRow(new String[] {
                        getLink(entity),
                        getRequired(entity),
                        entity.getDescription()
                }));
                // sbTexts.append("| " + getLink(entity) + " | " + getRequired(entity) + " | " + entity.getDescription() + " |\n");
                // sbTexts.append("*-------------------+-------*-------------------+\n");
                sbExemple.append("...");
            }
        }
        if (nbTexts > 0) {
            sbTexts.append(syntaxer.buildTableFooter());
            sb.append(sbTexts + "\n\n");
        }

        /* Fin de l'exemple */
        if (nbElements == 0 && nbTexts == 0) {
            sbExemple.deleteCharAt(sbExemple.length() - 1).append(" />\n");
        } else {
            sbExemple.append("</" + currentEntity.getType().getBaliseName() + ">\n");
        }
        sbExemple.append(syntaxer.buildQuoteEnd()).append("\n");
        if (!currentEntity.getType().isEnum()) {
            sb.append(sbExemple);
        }

        /* Classe d'implementation */
        if (currentEntity.getType().getName().indexOf(".") > -1) {
            String fullName = currentEntity.getType().getName();
            String packageName = fullName.substring(0, fullName.lastIndexOf("."));
            String className = fullName.substring(fullName.lastIndexOf(".") + 1);
            sb.append(syntaxer.buildUnorderedItem("Implémentation"));
            sb.append(syntaxer.buildTableHeader(2));
            sb.append(syntaxer.buildTableRow(new String[] {
                    syntaxer.fontBold("Package"),
                    packageName
            }));
            sb.append(syntaxer.buildTableRow(new String[] {
                    syntaxer.fontBold("Classe"),
                    className
            }));

            // sb.append("*----------+---------------------------------------------------------------+\n");
            // sb.append("| Package  | " + packageName + " |\n");
            // sb.append("*----------+---------------------------------------------------------------+\n");
            // sb.append("| Classe   | " + className + " |\n");
            // sb.append("*----------+---------------------------------------------------------------+\n\n");
            sb.append(syntaxer.buildTableFooter());
        }

        /* Documentation */
        String documentation = currentEntity.getType().getDocumentation();
        if (StringUtils.isNotBlank(documentation)) {
            StringBuffer sbDocumentation = new StringBuffer(syntaxer.buildUnorderedItem("Documentation"));
            sbDocumentation.append("    Une documentation complète est disponible {{{" + documentation + "}ici}}\n");
            sb.append(sbDocumentation);
        }

        /* Entités suivantes.... */
        itEntities = currentEntity.getEntities().keySet().iterator();
        while (itEntities.hasNext()) {
            String name = itEntities.next();
            SimpleXMLDocumentationEntity subEntity = currentEntity.getEntities().get(name);
            if (!subEntity.isPrimitive() && !alreadyDisplayed.contains(subEntity.getTypeName())) {
                alreadyDisplayed.add(subEntity.getTypeName());
                sb.append("\n\n\n" + format(subEntity, alreadyDisplayed));

            }
        }

        return sb.toString();
    }

    /*
     * (non-Javadoc)
     * 
     * @see org.tensin.beerduino.tools.ISimpleXMLDocumentation#generate(org.tensin.beerduino.tools.SimpleXMLDocumentationEntity)
     */
    /**
     * {@inheritDoc}
     * 
     * @see org.tensin.common.tools.documentation.updater.ISimpleXMLDocumentationOutput#generate(java.lang.Class, org.tensin.common.tools.documentation.updater.SimpleXMLDocumentationEntity)
     */
    @Override
    public String generate(final Class<?> racine, final SimpleXMLDocumentationEntity entity) throws SimpleXMLDocumentationException {
        syntaxer = new SyntaxerAPT();
        StringBuilder sb = new StringBuilder("{{Documentation}} ");
        sb.append("(" + getCurrentDateWithDateFormat("yyyy-MM-dd HH:mm:ss") + ")\n\n");
        sb.append(summaryInAPT(1, entity, 1));
        sb.append(format(entity, new TreeSet<String>()));
        return sb.toString();
    }

    /**
     * Gets the base replacement token.
     * 
     * @return the base replacement token
     */
    private String getBaseReplacementToken() {
        return baseReplacementToken;
    }

    /**
     * Méthode getCurrentDateWithDateFormat.
     * 
     * @param pattern
     *            the pattern
     * @return current date with date format
     *         String
     */
    public String getCurrentDateWithDateFormat(final String pattern) {
        return getDateWithDateFormat(pattern, new Date());
    }

    /**
     * Méthode getDateWithDateFormat.
     * 
     * @param pattern
     *            the pattern
     * @param date
     *            the date
     * @return the date with date format
     *         String
     */
    public String getDateWithDateFormat(final String pattern, final Date date) {
        final SimpleDateFormat dateFormat = new SimpleDateFormat(pattern);
        return dateFormat.format(date);
    }

    /**
     * Method.
     * 
     * @param entity
     *            the entity
     * @return the link
     */
    private String getLink(final SimpleXMLDocumentationEntity entity) {
        if (entity.isPrimitive()) {
            return entity.getType().getSimpleName();
        } else {
            return syntaxer.buildLink(entity.getType().getBaliseName(), entity.getType().getAnchor()); // "{{{" + entity.getType().getAnchor() + "}" + entity.getType().getBaliseName() + "}}";
        }
    }

    /**
     * Method.
     * 
     * @param entity
     *            the entity
     * @return the required
     */
    private String getRequired(final SimpleXMLDocumentationEntity entity) {
        if (entity.isRequired()) {
            return " X ";
        } else {
            return "   ";
        }
    }

    /**
     * Method.
     * 
     * @return the syntaxer
     */
    public ISyntaxer getSyntaxer() {
        return syntaxer;
    }

    /**
     * Checks if is mode merge.
     * 
     * @return true, if is mode merge {@inheritDoc}
     * @see org.tensin.common.tools.documentation.updater.ISimpleXMLDocumentationOutput#isModeMerge()
     */
    @Override
    public boolean isModeMerge() {
        return StringUtils.isNotEmpty(getBaseReplacementToken());
    }

    /**
     * {@inheritDoc}
     * 
     * @see org.tensin.common.tools.documentation.updater.ISimpleXMLDocumentationOutput#mergeContent(java.lang.Class, org.tensin.common.tools.documentation.updater.SimpleXMLDocumentationEntity, java.lang.String)
     */
    @Override
    public String mergeContent(final Class<?> racine, final SimpleXMLDocumentationEntity entity, final String sourceFileContent) throws SimpleXMLDocumentationException {
        String newContent = generate(racine, entity);

        String startToken = syntaxer.buildCommentStart(getBaseReplacementToken());
        String endToken = syntaxer.buildCommentEnd(getBaseReplacementToken());
        try {
            String existingContent = org.apache.commons.io.FileUtils.readFileToString(new File(sourceFileContent));
            return mergeContent(existingContent, newContent, startToken, endToken);
        } catch (IOException e) {
            throw new SimpleXMLDocumentationException(e);
        }

    }

    /**
     * Method.
     * 
     * @param existingContent
     *            the existing content
     * @param newContent
     *            the new content
     * @param startToken
     *            the start token
     * @param endToken
     *            the end token
     * @return the string
     */
    private String mergeContent(final String existingContent, final String newContent, final String startToken, final String endToken) {
        if (existingContent == null || StringUtils.isEmpty(startToken) || StringUtils.isEmpty(endToken)) {
            return null;
        }
        int strLen = existingContent.length();
        int openLen = startToken.length();
        int closeLen = endToken.length();
        StringBuilder sb = new StringBuilder();
        int pos = 0;
        int previousEnd = 0;
        while (pos < (strLen - closeLen)) {
            int start = existingContent.indexOf(startToken, pos);
            if (start < 0) {
                break;
            }
            start += openLen;
            int end = existingContent.indexOf(endToken, start);
            if (end < 0) {
                break;
            }
            sb.append(existingContent.substring(previousEnd, start)).append("\n");
            sb.append(newContent).append("\n");
            sb.append(endToken);
            pos = end + closeLen;
            previousEnd = pos;
        }
        // On copie la fin ...
        if (previousEnd >= 0) {
            sb.append(existingContent.subSequence(previousEnd, strLen));
        }

        return sb.toString();
    }

    /**
     * Sets the base replacement token.
     * 
     * @param baseReplacementToken
     *            the new base replacement token
     */
    public void setBaseReplacementToken(final String baseReplacementToken) {
        this.baseReplacementToken = baseReplacementToken;
    }

    /**
     * Method.
     * 
     * @param syntaxer
     *            the new syntaxer
     */
    public void setSyntaxer(final ISyntaxer syntaxer) {
        this.syntaxer = syntaxer;
    }

    /**
     * Method.
     * 
     * @param profondeur
     *            the profondeur
     * @param root
     *            the root
     * @param indice
     *            the indice
     * @return the string
     */
    private String summaryInAPT(final int profondeur, final SimpleXMLDocumentationEntity root, final int indice) {
        StringBuffer sb = new StringBuffer();
        sb.append("    " + StringUtils.repeat(" ", profondeur * 2) + "* {{{" + root.getType().getAnchor() + "}");
        sb.append(root.getType().getBaliseName() + "}}\n\n");
        Collection<SimpleXMLDocumentationEntity> subEntities = root.getEntities().values();
        for (SimpleXMLDocumentationEntity subEntity : subEntities) {
            if (subEntity.isElement() || subEntity.isElementList() || subEntity.isText()) {
                if (!subEntity.isPrimitive()) {
                    sb.append(summaryInAPT(profondeur + 1, subEntity, indice));
                }
            }
        }
        return sb.toString();
    }

}
